audetto/AppleWin

.travis.yml
CIBuild.bat

Attempt at building on Windows.

---

.gitmodules
source/frontends/sdl/CMakeLists.txt
source/frontends/sdl/main.cpp
source/linux/build.sh

Make ImGui a module.

---

linux.md
source/CMakeLists.txt
source/frontends/libretro/CMakeLists.txt
source/linux/config.h.in
source/linux/network/slirp2.cpp
source/linux/network/slirp2.h
source/linux/network/uthernet2.cpp

Allow compilation to work without libslirp (not available on Pi).

---

source/frontends/common2/fileregistry.cpp
source/frontends/common2/fileregistry.h
source/frontends/common2/utils.cpp
source/frontends/libretro/game.cpp
source/frontends/libretro/game.h
source/frontends/libretro/libretro.cpp
source/frontends/libretro/retroregistry.cpp
source/frontends/libretro/retroregistry.h
source/frontends/ncurses/main.cpp
source/frontends/ncurses/nframe.cpp
source/frontends/ncurses/nframe.h
source/frontends/sdl/main.cpp
source/linux/context.cpp
source/linux/context.h
source/linux/linuxframe.cpp
source/linux/windows/time.cpp

See https://github.com/audetto/AppleWin/issues/30

Various initialisation fixes

---

source/frontends/sdl/main.cpp

QEMU - Fedora 34. SDL_GL_SwapInterval always fails.

---

source/CMakeLists.txt
source/frontends/ncurses/CMakeLists.txt
source/frontends/sdl/CMakeLists.txt

Could solve https://github.com/audetto/AppleWin/issues/39.

Use cmake native find_package for OpenGL.

---

source/frontends/sdl/main.cpp

This will fix very slow speed on some SDL2 platforms
such as on Raspberry Pi 4 + Ubuntu22.04.

sa2: Fix for very slow speed

---

source/frontends/libretro/CMakeLists.txt
source/linux/raspbian.list.txt

complile/link corrections for lr-frontend on Pi OS Buster

---

.gitmodules
source/frontends/sdl/imgui/sdlsettings.cpp
source/frontends/sdl/imgui/sdlsettings.h
source/frontends/sdl/processfile.cpp

https://github.com/audetto/AppleWin/issues/118
It currently remembers the path of the last file dialog, but maybe better to open the same folder as the existing disk (if it exists).

sa2: add simple file browser.

---

source/frontends/common2/commonframe.cpp
source/frontends/common2/commonframe.h
source/frontends/common2/programoptions.cpp
source/frontends/common2/programoptions.h
source/frontends/libretro/game.cpp
source/frontends/libretro/game.h
source/frontends/libretro/retroframe.cpp
source/frontends/libretro/retroframe.h
source/frontends/ncurses/main.cpp
source/frontends/ncurses/nframe.cpp
source/frontends/ncurses/nframe.h
source/frontends/ncurses/world.cpp
source/frontends/ncurses/world.h
source/frontends/sdl/imgui/sdlimguiframe.cpp
source/frontends/sdl/imgui/sdlimguiframe.h
source/frontends/sdl/renderer/sdlrendererframe.cpp
source/frontends/sdl/renderer/sdlrendererframe.h
source/frontends/sdl/sdlframe.cpp
source/frontends/sdl/sdlframe.h

- moves SDLFrame code that's also used by the macOS port (https://github.com/sh95014/AppleWin/blob/master/source/frontends/mariani/MarianiFrame.cpp) up to CommonFrame.
**WARNING**: Builds and runs in sa2 (ImGui), but I don't know how well/poorly this does with your other frontends because I couldn't really build/test them.

Proposal: Refactor SDLFrame

---

source/frontends/common2/commonframe.cpp
source/frontends/common2/commonframe.h
source/frontends/common2/programoptions.cpp
source/frontends/common2/programoptions.h
source/frontends/common2/speed.cpp
source/frontends/common2/speed.h
source/frontends/ncurses/CMakeLists.txt
source/frontends/ncurses/main.cpp
source/frontends/ncurses/world.cpp
source/frontends/sdl/README.md
source/frontends/sdl/imgui/sdldebugger.h
source/frontends/sdl/imgui/sdlimguiframe.cpp
source/frontends/sdl/imgui/sdlsettings.cpp
source/frontends/sdl/main.cpp
source/frontends/sdl/renderer/sdlrendererframe.cpp
source/frontends/sdl/sdlframe.cpp
source/frontends/sdl/sdlframe.h
source/linux/benchmark.cpp
source/linux/cassettetape.h

Useful to `sa2` when running inside qemu.

Share synchronisation logic

---

source/SoundCore.cpp
source/frontends/libretro/game.cpp
source/frontends/libretro/game.h
source/frontends/libretro/rdirectsound.cpp
source/frontends/libretro/rdirectsound.h
source/frontends/libretro/retroregistry.cpp
source/frontends/libretro/retroregistry.h
source/frontends/sdl/imgui/sdlsettings.cpp
source/frontends/sdl/sdirectsound.cpp
source/frontends/sdl/sdirectsound.h
source/linux/libwindows/dsound.cpp
source/linux/libwindows/dsound.h

https://github.com/audetto/AppleWin/issues/139

ra2: re-add ability to differentiate audio source.

---

source/frontends/sdl/imgui/sdlsettings.cpp
source/frontends/sdl/imgui/sdlsettings.h
source/frontends/sdl/sdlframe.cpp

https://github.com/audetto/AppleWin/issues/149

sa2: add information about shortcuts.

---

source/frontends/common2/utils.cpp
source/frontends/common2/utils.h
source/frontends/libretro/game.cpp
source/frontends/libretro/retroframe.cpp
source/frontends/libretro/retroframe.h

https://github.com/audetto/AppleWin/issues/112

ra2: avoid side effects of chdir.

---

source/frontends/sdl/README.md
source/frontends/sdl/imgui/sdlimguiframe.cpp
source/frontends/sdl/imgui/sdlimguiframe.h
source/frontends/sdl/imgui/sdlsettings.cpp
source/frontends/sdl/imgui/sdlsettings.h
source/frontends/sdl/sdlframe.cpp
source/frontends/sdl/sdlframe.h

https://github.com/audetto/AppleWin/issues/149

sa2: better choice of hotkeys.

---

.github/README.md
source/frontends/common2/commonframe.cpp
source/frontends/common2/commonframe.h
source/frontends/common2/programoptions.cpp
source/frontends/common2/programoptions.h
source/frontends/ncurses/main.cpp
source/frontends/ncurses/nframe.cpp
source/frontends/qt/qtframe.cpp
source/frontends/sdl/imgui/sdlsettings.cpp
source/frontends/sdl/sdlframe.cpp
source/frontends/sdl/sdlframe.h
source/linux/context.cpp
source/linux/context.h
source/linux/linuxframe.cpp
source/linux/linuxframe.h

https://github.com/audetto/AppleWin/issues/143

Add --paused option to prevent boot.

---

source/frontends/sdl/CMakeLists.txt
source/frontends/sdl/imgui/cycletabitems.cpp
source/frontends/sdl/imgui/cycletabitems.h
source/frontends/sdl/imgui/inputtexthistory.cpp
source/frontends/sdl/imgui/inputtexthistory.h
source/frontends/sdl/imgui/sdldebugger.cpp
source/frontends/sdl/imgui/sdldebugger.h
source/frontends/sdl/imgui/sdlmemory.cpp
source/frontends/sdl/imgui/sdlmemory.h
source/frontends/sdl/imgui/sdlsettings.cpp
source/frontends/sdl/imgui/sdlsettings.h
source/frontends/sdl/imgui/settingshelper.cpp
source/frontends/sdl/imgui/settingshelper.h

https://github.com/audetto/AppleWin/issues/156

sa2 debugger: add some shortcuts.

---

source/CMakeLists.txt
source/frontends/sdl/imgui/sdlsettings.cpp
source/frontends/sdl/sdlframe.cpp
source/linux/config.h.in
source/linux/duplicates/tfearch.cpp
source/linux/linuxframe.cpp
source/linux/raspbian.list.txt

Moreover, allow to build without slirp and pcap.
https://github.com/audetto/AppleWin/issues/140

pcap: drop requirement.

---

CMakeLists.txt

Fixes https://github.com/audetto/AppleWin/issues/195

Disable IPO.

---

.github/README.md
.github/workflows/build.yaml
CMakeLists.txt
source/frontends/qt/CMakeLists.txt
source/frontends/qt/audioinfo.cpp
source/frontends/qt/options.cpp
source/frontends/qt/preferences.cpp
source/frontends/qt/qapple.cpp
source/frontends/qt/qdirectsound.cpp
source/frontends/qt/qdirectsound.h
source/frontends/qt/qvideo.cpp
source/linux/raspbian.list.txt

Initial version: no audio no gamepad.
https://github.com/audetto/AppleWin/issues/203

qapple to qt6.

---

CMakeLists.txt
source/CMakeLists.txt
source/frontends/common2/CMakeLists.txt
source/frontends/libretro/CMakeLists.txt
source/frontends/libretro/game.cpp
source/frontends/libretro/retroregistry.cpp
source/frontends/qt/CMakeLists.txt
source/frontends/sdl/CMakeLists.txt
source/linux/linuxframe.cpp
source/linux/linuxframe.h
source/linux/registryclass.cpp
source/linux/registryclass.h
test/TestCPU6502/CMakeLists.txt

https://github.com/audetto/AppleWin/issues/49

A few simple Win32 fixes.

---

.github/README.md
CMakeLists.txt
source/CMakeLists.txt
source/StdAfx.h
source/frontends/common2/fileregistry.cpp
source/frontends/common2/gnuframe.cpp
source/frontends/libretro/diskcontrol.cpp
source/frontends/libretro/environment.cpp
source/frontends/libretro/serialisation.cpp
source/frontends/ncurses/CMakeLists.txt
source/frontends/ncurses/evdevpaddle.cpp
source/linux/msys2.md
source/linux/network/portfwds.cpp
source/linux/network/portfwds.h
test/TestCPU6502/stdafx.h

At this point I am looking for the minimum amount of changes to make it compile and work.
With this I can compile up to up to `applewin_libretro`.
Changes of behaviour to be more or better will happen at a later stage.

msys2-mingw64: changes to compile the retro core.

---

source/frontends/common2/argparser.cpp
source/frontends/common2/commonframe.cpp
source/frontends/common2/fileregistry.cpp
source/frontends/common2/fileregistry.h
source/frontends/common2/gnuframe.cpp
source/frontends/common2/gnuframe.h
source/frontends/common2/programoptions.cpp
source/frontends/common2/programoptions.h
source/frontends/common2/ptreeregistry.cpp
source/frontends/common2/ptreeregistry.h
source/frontends/common2/utils.cpp
source/frontends/common2/utils.h
source/frontends/qt/configuration.cpp
source/frontends/qt/configuration.h
source/frontends/sdl/README.md
source/frontends/sdl/imgui/sdlimguiframe.cpp
source/frontends/sdl/imgui/sdlsettings.cpp
source/frontends/sdl/imgui/settingshelper.cpp
source/frontends/sdl/imgui/settingshelper.h
source/linux/msys2.md
source/linux/registryclass.h

To reduce platform differences.

Use C++ filesystem API.

---

source/frontends/ncurses/CMakeLists.txt
source/frontends/ncurses/applen_config.h.in
source/frontends/ncurses/evdevpaddle.cpp

See https://github.com/sh95014/AppleWin/issues/62

applen: add ability to build without libevdev.
